### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Vrublevskaya1** [OrlovAndrei/RKIS#100]
[Документ Microsoft Word.docx](https://github.com/user-attachments/files/17545005/Microsoft.Word.docx)
Здравствуйте, такая проблема: не получается клонировать репозиторий. Пыталась это сделать через VS, но не получилось, он начинает клонироваться, но потом возникает ошибка. Пробовала через командную строку, тут уже другая ошибка, что гит не распознается (в PS тоже самое). Потом скачала гит десктоп, пробовала клонировать репозиторий через него и все равно возникает точно такая же ошибка, как и в VS. В прикрепленном файле все показано.

**Comment by savitar696** [comment]
Установи Git

**Comment by Vrublevskaya1** [comment]
> Установи Git https://git-scm.com/downloads

Спасибо
